# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 811bb03f33843680b6ed249c9c11b4dcbb1b13f5ee6db2b3ae31ca6f11f992fd4745be079e937408145130fc3ef08db86e6f07fcf0dc1ab603e78f2f8704ee5f

test:
  secret_key_base: 0e3f1c23c559d309a18f261ff84fbeb8ac60e29b6fe10b4c123489eefb3883c40c6738df3abfbaf5e4df9d90df54af38c39a28174919403bddfd0d498cb2cc47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
